# URL do banco (altere host, port, database)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/femass-requerimento
quarkus.datasource.username=postgres
quarkus.datasource.password=femass-requerimento

quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.format-sql=true

# CORS (dev local front-end)
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=authorization,content-type,accept,origin
quarkus.http.cors.exposed-headers=authorization,location,content-type,accept
quarkus.http.cors.access-control-max-age=24H
quarkus.http.cors.access-control-allow-credentials=true

quarkus.hibernate-orm.schema-management.strategy=update
%test.quarkus.hibernate-orm.schema-management.strategy=drop-and-create


# OIDC / Keycloak dev services (local test realm)
quarkus.keycloak.devservices.enabled=false
quarkus.datasource.devservices.enabled=false
quarkus.keycloak.devservices.realm-path=quarkus-realm.json

# Local OIDC endpoints
quarkus.oidc.auth-server-url=http://localhost:8130/realms/quarkus
quarkus.oidc.client-id=backend-service
quarkus.oidc.credentials.secret=
quarkus.oidc.application-type=service



# Para uso de REST Client OAuth2 (service to service)
quarkus.oidc-client.auth-server-url=http://localhost:8130/realms/quarkus
quarkus.oidc-client.client-id=backend-service
quarkus.oidc-client.credentials.secret=
quarkus.oidc-client.grant.type=client

# Dev logging: be more verbose for troubleshooting
quarkus.log.level=INFO
quarkus.log.category."org.petrohub".level=INFO
quarkus.log.category."io.quarkus.scheduler".level=DEBUG
quarkus.log.category."io.quarkus.oidc".level=DEBUG
